name: Test GitHub Action
on: [pull_request]

jobs:
  test-github-action:
    name: Test GitHub Action
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: john-d-pelingo/jira-link-issue-action@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          atlassian-domain: 'https://johndpelingo.atlassian.net'
          board-name: 'MEME'
